-- SQL statements to create tables in Supabase
-- Copy and paste these into the Supabase SQL Editor

-- Table: nep_master_user_table_sample_data
-- Source: csvfiles/nep_master_user_table_sample_data.csv
CREATE TABLE IF NOT EXISTS nep_master_user_table_sample_data (
  "user_id" VARCHAR(500),
  "login_status" VARCHAR(500),
  "profile_status" VARCHAR(500),
  "phone_status" VARCHAR(500),
  "activity_date" VARCHAR(500),
  "created_datetime" VARCHAR(500),
  "otp_verified_date" VARCHAR(500),
  "otp_verified_datetime" VARCHAR(500),
  "profile_user_id" VARCHAR(500),
  "user_uuid" VARCHAR(500),
  "user_email" VARCHAR(500),
  "user_first_name" VARCHAR(500),
  "user_last_name" VARCHAR(500),
  "user_profile_status" VARCHAR(500),
  "user_country_code" BIGINT,
  "user_phone_number" BIGINT,
  "user_preferred_language" VARCHAR(500),
  "user_profile_completion_date" VARCHAR(500),
  "user_type" VARCHAR(500),
  "company_type" VARCHAR(500),
  "company_revenue_range" VARCHAR(500),
  "user_type_datekey1" VARCHAR(500),
  "user_type_datekey2" VARCHAR(500),
  "traffic_source_source" VARCHAR(500),
  "traffic_source_medium" VARCHAR(500),
  "traffic_source_campaign" VARCHAR(500),
  "user_profile_updated_date" VARCHAR(500),
  "user_role" VARCHAR(500),
  "user_beta_feature" DOUBLE PRECISION,
  "user_language_proficiency" DOUBLE PRECISION,
  "message_user_id" VARCHAR(500),
  "se_me_re_user_id" VARCHAR(500),
  "jc_user_id" VARCHAR(500)
);


-- Table: nep_master_live_events_data
-- Source: csvfiles/nep_master_live_events_data.csv
CREATE TABLE IF NOT EXISTS nep_master_live_events_data (
  "event_id" VARCHAR(500),
  "event_title" VARCHAR(500),
  "event_status" VARCHAR(500),
  "country" DOUBLE PRECISION,
  "provider" VARCHAR(500),
  "organizer_id" VARCHAR(500),
  "client_name" VARCHAR(500),
  "description" TEXT,
  "invite_type" VARCHAR(500),
  "zoom_meeting_id" BIGINT,
  "participants_limit" BIGINT,
  "start_datetime" VARCHAR(500),
  "start_date" VARCHAR(500),
  "end_datetime" VARCHAR(500),
  "language" VARCHAR(500),
  "program_key" VARCHAR(500),
  "gapkey" VARCHAR(500),
  "topickey" VARCHAR(500),
  "sessiontype" VARCHAR(500),
  "created_at" VARCHAR(500),
  "updated_at" VARCHAR(500),
  "speaker_name" VARCHAR(500),
  "speaker_email" VARCHAR(500),
  "speaker_bio" DOUBLE PRECISION,
  "event_type" VARCHAR(500),
  "participant_id" VARCHAR(500),
  "participant_status" VARCHAR(500),
  "participant_created_at" VARCHAR(500),
  "participant_updated_at" VARCHAR(500),
  "metadata_id" DOUBLE PRECISION,
  "metadata_topic" VARCHAR(500),
  "metadata_join_url" VARCHAR(500),
  "metadata_start_time" VARCHAR(500),
  "metadata_registrant_id" VARCHAR(500),
  "participant_email" VARCHAR(500),
  "participant_user_id" VARCHAR(500),
  "participant_client_name" VARCHAR(500),
  "participant_first_name" VARCHAR(500),
  "participant_last_name" VARCHAR(500),
  "particpant_country" VARCHAR(500),
  "rating_user_response_value" DOUBLE PRECISION,
  "rating_user_response_text" DOUBLE PRECISION,
  "feedback_user_id" DOUBLE PRECISION,
  "organiser_name" DOUBLE PRECISION
);


-- Table: nep_liftoffx_data_sample
-- Source: csvfiles/nep_liftoffX_data_sample.csv
CREATE TABLE IF NOT EXISTS nep_liftoffx_data_sample (
  "last_active" BIGINT,
  "week_activity_number" BIGINT,
  "month_activity_number" BIGINT,
  "signup_year_monthnumber_weekstart_order" BIGINT,
  "year_monthnumber_weekstart_order" BIGINT,
  "signup_date" VARCHAR(500),
  "signup_month_name" VARCHAR(500),
  "signup_month_number" BIGINT,
  "user_type_datekey" VARCHAR(500),
  "userid" VARCHAR(500),
  "user_email" VARCHAR(500),
  "user_first_name" VARCHAR(500),
  "user_last_name" VARCHAR(500),
  "company_type" VARCHAR(500),
  "company_revenue_range" VARCHAR(500),
  "created_at" VARCHAR(500),
  "activity_id" VARCHAR(500),
  "activity_type" VARCHAR(500),
  "activity_tittle" VARCHAR(500),
  "conversation_id" VARCHAR(500),
  "conversation_parent_id" DOUBLE PRECISION,
  "message_query" VARCHAR(500),
  "message_query_id" VARCHAR(500),
  "message_rating" DOUBLE PRECISION,
  "message_rating_feedback" DOUBLE PRECISION,
  "response_type" VARCHAR(500),
  "response_content" TEXT,
  "response_timestamp" VARCHAR(500),
  "response_flow_state" VARCHAR(500),
  "response_metricsblob" VARCHAR(500),
  "message_date" VARCHAR(500),
  "session_rating" DOUBLE PRECISION,
  "mentor_rating" DOUBLE PRECISION,
  "resources_rating" DOUBLE PRECISION,
  "mentor_id" DOUBLE PRECISION,
  "mentor_name" DOUBLE PRECISION,
  "mentor_email" DOUBLE PRECISION,
  "connection_reason" DOUBLE PRECISION,
  "event_id" DOUBLE PRECISION,
  "event_date" DOUBLE PRECISION,
  "event_time" DOUBLE PRECISION,
  "event_source" DOUBLE PRECISION,
  "event_speaker" DOUBLE PRECISION,
  "event_gap_area" DOUBLE PRECISION,
  "expert_session_topic" DOUBLE PRECISION,
  "ga_session_id" DOUBLE PRECISION,
  "ga_event_name" VARCHAR(500),
  "ga_event_date" VARCHAR(500),
  "user_type" VARCHAR(500),
  "traffic_source_source" VARCHAR(500),
  "traffic_source_medium" VARCHAR(500),
  "traffic_source_campaign" VARCHAR(500),
  "month_year" VARCHAR(500),
  "month_year_order" BIGINT,
  "signup_month_year" VARCHAR(500),
  "signup_month_year_order" BIGINT,
  "signup_year" BIGINT,
  "month_name" VARCHAR(500),
  "month_number" BIGINT,
  "week_range" VARCHAR(500),
  "signup_week_range" VARCHAR(500)
);


-- Table: nep_mentor_profiles_sample_data
-- Source: csvfiles/nep_mentor_profiles_sample_data.csv
CREATE TABLE IF NOT EXISTS nep_mentor_profiles_sample_data (
  "_id" VARCHAR(500),
  "user_id" VARCHAR(500),
  "first_name" VARCHAR(500),
  "last_name" VARCHAR(500),
  "email" VARCHAR(500),
  "title" VARCHAR(500),
  "bio" TEXT,
  "user_status" VARCHAR(500),
  "visibility" VARCHAR(500),
  "preferred_language" VARCHAR(500),
  "created_at" VARCHAR(500),
  "updated_at" VARCHAR(500),
  "deleted" BOOLEAN,
  "company_type" VARCHAR(500),
  "linkedin_url" TEXT,
  "profile_image_url" VARCHAR(500),
  "country" VARCHAR(500),
  "state" VARCHAR(500),
  "city" VARCHAR(500),
  "role" VARCHAR(500),
  "mentor_type" VARCHAR(500),
  "program" VARCHAR(500),
  "language_known" DOUBLE PRECISION,
  "stage_id" BIGINT,
  "stage_name" VARCHAR(500),
  "industry_id" DOUBLE PRECISION,
  "industry_name" VARCHAR(500),
  "degree" VARCHAR(500),
  "institute_name" VARCHAR(500),
  "edu_start_date" VARCHAR(500),
  "graduation_date" VARCHAR(500),
  "employer_name" VARCHAR(500),
  "employment_sector" VARCHAR(500),
  "emp_start_date" VARCHAR(500),
  "emp_end_date" VARCHAR(500)
);


