[build]
  base    = "chat_ui"
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "API_SECRET_KEY"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
